[options]
admin_passwd = $pbkdf2-sha512$600000$MibkHENICeH837tXqnVuDQ$aAkTKsDFdyw6fCITFcMFUiyN1qgTH8aOB1NQ5I6NoMMgVJ4hyL7hy5F4tXGBSwGPS7x1f7N5pE3gQGSXDXpWkA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons

