[options]
admin_passwd = $pbkdf2-sha512$600000$753TOkdIiXEOIcQ4Z0zpfQ$QA23nkfxOCYxk4.f/7uIcyxQj9B95JURjEpkrMsTLO65nYRMSp./jatkhsqpPUhaCsj./Uz4x0SdCBT8yF/U7Q
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons

